addr: ":8084"
imagePullSecrets: aliyunrepo
watchTimeout: 1
callBackURL: "http://10.0.116.233:8080/api/hooks/k8s/callback"
resource:
  requests:
    memory: 100Mi
    cpu: 50m
  limits:
    memory: 300Mi
    cpu: 1000m